# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-24 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Feature', 'Feature'), ('Short', 'Short'), ('Doc', 'Documentary')], max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('cast', models.CharField(blank=True, max_length=120)),
                ('director', models.CharField(blank=True, max_length=30)),
                ('metascore', models.CharField(blank=True, max_length=10)),
                ('meter', models.CharField(blank=True, max_length=10)),
                ('synopsis', models.TextField(blank=True)),
                ('intdes1', models.ImageField(blank=True, null=True, upload_to='intdes')),
                ('intdes2', models.ImageField(blank=True, null=True, upload_to='intdes')),
                ('foodmen1', models.ImageField(blank=True, null=True, upload_to='foodmen')),
                ('foodmen2', models.ImageField(blank=True, null=True, upload_to='foodmen')),
                ('location1', models.ImageField(blank=True, null=True, upload_to='location')),
                ('location2', models.ImageField(blank=True, null=True, upload_to='location')),
                ('cinto', models.TextField(blank=True)),
                ('trivia', models.TextField(blank=True)),
                ('popref', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
