# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-26 06:46
from __future__ import unicode_literals

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemabook',
            name='mcurl',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='cinemabook',
            name='rturl',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='cinemabook',
            name='verify',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cinemabook',
            name='wpurl',
            field=models.URLField(blank=True, editable=False),
        ),
    ]
