# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-26 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20180926_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemabook',
            name='mcurl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='cinemabook',
            name='rturl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='cinemabook',
            name='wpurl',
            field=models.URLField(blank=True),
        ),
    ]
