# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-26 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20180926_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemabook',
            name='trivia',
        ),
    ]
