# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-26 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_remove_cinemabook_trivia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cinema', models.ManyToManyField(to='cinema.CinemaBook')),
            ],
        ),
    ]
