# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-26 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cinema',
        ),
        migrations.AlterField(
            model_name='cinemabook',
            name='language',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
