# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20180926_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemabook',
            name='dialogs',
            field=models.TextField(blank=True),
        ),
    ]
