# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-27 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0007_cinemabook_dialogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('cinema',),
            },
        ),
        migrations.AlterModelOptions(
            name='cinemabook',
            options={'ordering': ('timestamp', 'name')},
        ),
        migrations.AddField(
            model_name='designshot',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.CinemaBook'),
        ),
        migrations.AddField(
            model_name='designshot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
