# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-27 13:40
from __future__ import unicode_literals

import cinema.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0008_auto_20180927_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fimage', models.ImageField(blank=True, upload_to=cinema.models.FoodShot.update_foodmen_file)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.CinemaBook')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('cinema',),
            },
        ),
        migrations.CreateModel(
            name='LocationShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limage', models.ImageField(blank=True, upload_to=cinema.models.LocationShot.update_location_file)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.CinemaBook')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('cinema',),
            },
        ),
        migrations.RemoveField(
            model_name='designshot',
            name='image',
        ),
        migrations.AddField(
            model_name='designshot',
            name='dimage',
            field=models.ImageField(blank=True, upload_to=cinema.models.DesignShot.update_intdes_file),
        ),
    ]
