# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-27 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_auto_20180927_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemabook',
            name='foodmen1',
            field=models.ImageField(blank=True, null=True, upload_to='x'),
        ),
        migrations.AddField(
            model_name='cinemabook',
            name='foodmen2',
            field=models.ImageField(blank=True, null=True, upload_to='x'),
        ),
        migrations.AddField(
            model_name='cinemabook',
            name='intdes1',
            field=models.ImageField(blank=True, null=True, upload_to='x'),
        ),
        migrations.AddField(
            model_name='cinemabook',
            name='intdes2',
            field=models.ImageField(blank=True, null=True, upload_to='x'),
        ),
        migrations.AddField(
            model_name='cinemabook',
            name='location1',
            field=models.ImageField(blank=True, null=True, upload_to='x'),
        ),
        migrations.AddField(
            model_name='cinemabook',
            name='location2',
            field=models.ImageField(blank=True, null=True, upload_to='x'),
        ),
    ]
