# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-27 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_auto_20180927_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemabook',
            name='mcurl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cinemabook',
            name='rturl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cinemabook',
            name='verify',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cinemabook',
            name='wpurl',
            field=models.URLField(blank=True),
        ),
    ]
