# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-27 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_auto_20180927_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemabook',
            name='foodmen1',
        ),
        migrations.RemoveField(
            model_name='cinemabook',
            name='foodmen2',
        ),
        migrations.RemoveField(
            model_name='cinemabook',
            name='intdes1',
        ),
        migrations.RemoveField(
            model_name='cinemabook',
            name='intdes2',
        ),
        migrations.RemoveField(
            model_name='cinemabook',
            name='location1',
        ),
        migrations.RemoveField(
            model_name='cinemabook',
            name='location2',
        ),
    ]
