# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-28 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_auto_20180927_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemabook',
            options={'ordering': ('-timestamp', 'name')},
        ),
    ]
