# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-29 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_auto_20180929_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemabook',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=40),
        ),
    ]
