# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-17 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0019_beginnings_endings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemabook',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
