# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-17 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0020_cinemabook_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemabook',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
