# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-29 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0021_auto_20181017_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemabook',
            name='cast',
            field=models.CharField(blank=True, max_length=420),
        ),
    ]
