# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-29 10:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0022_auto_20181029_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemabook',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
