# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-18 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0006_auto_20180918_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athenacard',
            old_name='birth',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='athenacard',
            name='rating',
        ),
        migrations.AddField(
            model_name='athenacard',
            name='details',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='athenacard',
            name='mugshot',
            field=models.ImageField(blank=True, max_length=120, null=True, upload_to='cardimg'),
        ),
    ]
