# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-18 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0007_auto_20180918_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athenacard',
            name='category',
            field=models.CharField(choices=[('BN', 'Bengali'), ('IN', 'Indian'), ('IT', 'Italian'), ('AM', 'American'), ('AS', 'Asian'), ('BR', 'British')], max_length=2),
        ),
    ]
