# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-18 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0008_auto_20180918_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athenacard',
            name='details',
            field=models.CharField(blank=True, help_text='Ingredients and/or origin story.', max_length=200),
        ),
        migrations.AlterField(
            model_name='athenacard',
            name='price',
            field=models.CharField(help_text='Enter price in INR.', max_length=120),
        ),
    ]
