# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-18 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0009_auto_20180918_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athenacard',
            name='details',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='athenacard',
            name='price',
            field=models.CharField(max_length=120),
        ),
    ]
