# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-26 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0014_auto_20180918_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athenacard',
            name='category',
            field=models.CharField(choices=[('tandoori', 'Tandoori'), ('cold_beverage', 'Cold Beverage'), ('italian', 'Italian'), ('healthy', 'Healthy'), ('dessert', 'Dessert'), ('specialties', 'Specialties')], max_length=2),
        ),
    ]
