# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-17 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0017_auto_20180929_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athenacard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='athenacard',
            name='price',
        ),
        migrations.AddField(
            model_name='athenacard',
            name='bazooka',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='athenacard',
            name='body',
            field=models.CharField(choices=[('b', 'B'), ('bb', 'B+')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='athenacard',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='athenacard',
            name='face',
            field=models.CharField(choices=[('l', 'L'), ('ll', 'L+')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='athenacard',
            name='roots',
            field=models.CharField(choices=[('sa', 'South Asian'), ('wo', 'World')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='athenacard',
            name='tushy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='athenacard',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athenacard',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
