# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0020_athenacard_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athenacard',
            options={'ordering': ('dob',)},
        ),
        migrations.AddField(
            model_name='athenacard',
            name='details',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
