# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-18 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0021_auto_20181218_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athenacard',
            name='details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
