# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0022_auto_20181218_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athenacard',
            name='dob',
            field=models.DateField(default='01/01/89', null=True),
        ),
    ]
