# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-18 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0024_auto_20181218_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athenacard',
            options={'ordering': ('-dob',)},
        ),
    ]
