# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-19 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0026_auto_20181219_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athenarank',
            options={'ordering': ('rank',)},
        ),
    ]
