# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-19 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0027_auto_20181219_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athenacard',
            options={'ordering': ('timestamp',)},
        ),
    ]
