# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0028_auto_20181219_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='athenacard',
            name='imcomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='athenacard',
            name='body',
            field=models.CharField(blank=True, choices=[('b', 'B'), ('bb', 'B+')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='athenacard',
            name='dob',
            field=models.DateField(default='01/01/89', null=True),
        ),
        migrations.AlterField(
            model_name='athenacard',
            name='face',
            field=models.CharField(blank=True, choices=[('l', 'L'), ('ll', 'L+')], max_length=5, null=True),
        ),
    ]
