# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-24 19:31
from __future__ import unicode_literals

import athena.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0030_auto_20181219_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthenaVideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.FileField(null=True, upload_to=athena.models.AthenaVideoFile.update_vid_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'avi', '3gp'])])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.AddField(
            model_name='athenacard',
            name='vid',
            field=models.FileField(blank=True, null=True, upload_to=athena.models.AthenaCard.update_vid_file),
        ),
        migrations.AddField(
            model_name='athenavideofile',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.AthenaCard'),
        ),
    ]
