# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-24 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0032_auto_20190425_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='athenacard',
            name='vid1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athenacard',
            name='vid2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athenacard',
            name='vid3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athenacard',
            name='vid4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
