# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-24 20:33
from __future__ import unicode_literals

import athena.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0034_athenaimagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='athenacard',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=athena.models.AthenaCard.update_img_file),
        ),
    ]
